trigger:
- master  # Adjust the branch as needed

pool:
  vmImage: 'ubuntu-latest'  # You can choose a different image depending on your requirements

variables:
  buildConfiguration: 'Release'  

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: 'Build and Test'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET 8'
      inputs:
        packageType: 'sdk'
        version: '8.x'
        
    - task: NuGetCommand@2
      displayName: 'Restore NuGet Packages'
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      displayName: 'Build Project'
      inputs:
        command: 'build'
        projects: '**/CodeCube.Azure.Storage.csproj'
        arguments: '--configuration $(buildConfiguration)'
    
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/CodeCube.Azure.Storage.csproj'
        arguments: '--configuration $(buildConfiguration)'

- stage: Deploy
  jobs:
  - job: Deploy
    displayName: 'Deploy to NuGet'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'
        
    - script: dotnet pack --configuration $(buildConfiguration)
      displayName: 'Pack NuGet package'

    - task: NuGetCommand@2
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'nuget.org'
