trigger:
- master  # Adjust the branch as needed

pool:
  vmImage: 'ubuntu-latest'  # You can choose a different image depending on your requirements

variables:
  buildConfiguration: 'Release'
  Version.Major: '4'
  Version.Minor: '0'
  ProjectToPack: 'CodeCube.Azure.Storage.csproj'
  system.debug: false

name: $(Version.Major).$(Version.Minor).$(Rev:r)

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: 'Build and Test'
    steps:
    - task: Assembly-Info-NetCore@3
      inputs:
        PackageId: CodeCube.Azure.Storage
        Authors: 'Rob Lohmann'
        Company: 'Rob Lohmann'
        Product: CodeCube.Azure.Storage
        Copyright: 'Copyright © 2019 - 2025 by Rob Lohmann'
        VersionNumber: '$(Build.BuildNumber)'
        FileVersionNumber: '$(Build.BuildNumber)'
        InformationalVersion: '$(Build.BuildNumber)'
        PackageVersion: '$(Build.BuildNumber)'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: restore
        projects: '**/$(ProjectToPack)'
        verbosityRestore: Detailed
        verbosityPack: Detailed
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        projects: '**/$(ProjectToPack)'
        arguments: '--configuration $(BuildConfiguration)'
        verbosityRestore: Detailed
        verbosityPack: Detailed
    - task: DotNetCoreCLI@2
      displayName: 'dotnet test'
      inputs:
        command: test
        projects: '**/*.Tests.csproj'
        arguments: '--configuration $(BuildConfiguration)'
        verbosityRestore: Detailed
        verbosityPack: Detailed
    - task: DotNetCoreCLI@2
      displayName: 'dotnet pack'
      inputs:
        command: pack
        verbosityRestore: Detailed
        versioningScheme: byBuildNumber
        verbosityPack: Detailed
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'